title: Farah Sayari
logo: /assets/img/img.png
theme: jekyll-theme-minimal
description: First-year engineering student with a keen interest in data science and artificial intelligence.
show_downloads: false
